from collections.abc import Sequence
import enum


class BufferKind(enum.Enum):
    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

    WORKSPACE = 0

    CONSTANT = 1

    INPUT = 2

    OUTPUT = 3

    @property
    def is_io(self) -> bool: ...

    def __hash__(self) -> int: ...

class Allocation:
    def __init__(self, id: int | str, size: int, start: int, end: int, offset: int | None = None, kind: BufferKind | None = None) -> None: ...

    @property
    def id(self) -> int | str: ...

    @property
    def size(self) -> int: ...

    @property
    def start(self) -> int: ...

    @property
    def end(self) -> int: ...

    @property
    def offset(self) -> int | None: ...

    @property
    def kind(self) -> BufferKind | None: ...

    @property
    def is_allocated(self) -> bool: ...

    @property
    def duration(self) -> int: ...

    @property
    def height(self) -> int | None: ...

    @property
    def area(self) -> int: ...

    def overlaps_temporally(self, other: Allocation) -> bool: ...

    def overlaps_spatially(self, other: Allocation) -> bool: ...

    def overlaps(self, other: Allocation) -> bool: ...

    def with_offset(self, offset: int) -> Allocation: ...

    def with_kind(self, kind: BufferKind) -> Allocation: ...

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

    def __eq__(self, arg: Allocation, /) -> bool: ...

    def __hash__(self) -> int: ...

class GreedyAllocatorCpp:
    def __init__(self) -> None: ...

    def allocate(self, allocations: Sequence[Allocation]) -> list[Allocation]: ...

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...

    def __eq__(self, arg: GreedyAllocatorCpp, /) -> bool: ...

    def __hash__(self) -> int: ...

class SearchOptions:
    def __init__(self) -> None: ...

    @property
    def canonical(self) -> bool: ...

    @canonical.setter
    def canonical(self, arg: bool, /) -> None: ...

    @property
    def dominance(self) -> bool: ...

    @dominance.setter
    def dominance(self, arg: bool, /) -> None: ...

    @property
    def floor_inference(self) -> bool: ...

    @floor_inference.setter
    def floor_inference(self, arg: bool, /) -> None: ...

    @property
    def monotonic_floor(self) -> bool: ...

    @monotonic_floor.setter
    def monotonic_floor(self, arg: bool, /) -> None: ...

    @property
    def decompose(self) -> bool: ...

    @decompose.setter
    def decompose(self, arg: bool, /) -> None: ...

class Partition:
    @staticmethod
    def from_allocations(allocations: Sequence[Allocation]) -> Partition: ...

    def static_sort(self, heuristic: str) -> Partition: ...

    def with_best_height(self, height: int) -> Partition: ...

    @property
    def lower_bound(self) -> int: ...

    @property
    def height(self) -> int: ...

    @property
    def allocations(self) -> list[Allocation]: ...

    def allocated_offset(self, allocation: Allocation) -> int: ...

def solve_many(partitions: Sequence[Partition], node_limit: int, max_seconds: float, best_bound: int, options: SearchOptions = ..., num_threads: int = 1, heuristics: Sequence[str] = []) -> Partition | None: ...
